/** Kenney UI pack RPG extension — atlas frame names. */
export const UI = {
  PANEL: 'panel_beige.png',
  PANEL_LIGHT: 'panel_beigeLight.png',
  PANEL_BROWN: 'panel_brown.png',
  INSET: 'panelInset_beige.png',
  INSET_BROWN: 'panelInset_brown.png',
  BTN_LONG: 'buttonLong_beige.png',
  BTN_LONG_PRESS: 'buttonLong_beige_pressed.png',
  BTN_BROWN: 'buttonLong_brown.png',
  BTN_SQ: 'buttonSquare_beige.png',
  BTN_SQ_PRESS: 'buttonSquare_beige_pressed.png',
  BTN_ROUND: 'buttonRound_beige.png',
  CROSS: 'iconCross_brown.png',
  CHECK: 'iconCheck_bronze.png',
  BAR_BACK_L: 'barBack_horizontalLeft.png',
  BAR_BACK_M: 'barBack_horizontalMid.png',
  BAR_BACK_R: 'barBack_horizontalRight.png',
  BAR_RED_L: 'barRed_horizontalLeft.png',
  BAR_RED_M: 'barRed_horizontalMid.png',
  BAR_RED_R: 'barRed_horizontalRight.png',
  BAR_GREEN_L: 'barGreen_horizontalLeft.png',
  BAR_GREEN_M: 'barGreen_horizontalMid.png',
  BAR_GREEN_R: 'barGreen_horizontalRight.png',
};
